export const constituencies = [
    { id: 'westlands', name: 'Westlands' },
    { id: 'dagoretti-north', name: 'Dagoretti North' },
    { id: 'dagoretti-south', name: 'Dagoretti South' },
    { id: 'langata', name: 'Langata' },
    { id: 'kibra', name: 'Kibra' },
    { id: 'roysambu', name: 'Roysambu' },
    { id: 'kasarani', name: 'Kasarani' },
    { id: 'ruarak', name: 'Ruaraka' },
    { id: 'embakasi-south', name: 'Embakasi South' },
    { id: 'embakasi-north', name: 'Embakasi North' },
    { id: 'embakasi-central', name: 'Embakasi Central' },
    { id: 'embakasi-east', name: 'Embakasi East' },
    { id: 'embakasi-west', name: 'Embakasi West' },
    { id: 'makadara', name: 'Makadara' },
    { id: 'kamukunji', name: 'Kamukunji' },
    { id: 'starehe', name: 'Starehe' },
    { id: 'mathare', name: 'Mathare' },
];
